### ISSUE TITLE
[Doc] Update Gitjob documentation

### ISSUE THREAD

**Issue by mmartin24** [epinio/docs#251]
## Issue
It is not possible to push with gitjob following instructions https://docs.epinio.io/howtos/gitjob_push.
We need to update the docs with working steps

The following updates seemed to have worked:
- When deploying from Rancher Epinio does not have a namespace created; so it is needed to create it and target it

- Changes on the `serviceaccount.yaml`:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: epinio-gitjob
```

- Summary of changes on `12factor-gitjob.yaml`:

  - updates on image [ghcr.io/epinio/epinio-server:v1.8.1](http://ghcr.io/epinio/epinio-server:v1.8.1)
  - updates on args (`--name`)
  - updates on env `EPINIO_SETTINGS`
  - Additions on volumes and volumeMounts

```yaml
apiVersion: gitjob.cattle.io/v1
kind: GitJob
metadata:
  # The name of the GitJob, doesn't need to match the project.
  name: samplepush
spec:
  syncInterval: 15
  git:
    # The git repo and branch to track. 
    repo: https://github.com/epinio/example-12factor
    branch: main
  jobSpec:
    template:
      spec:
        # This should match what we created in the last step
        serviceAccountName: epinio-gitjob
        restartPolicy: "Never"
        containers:
        # This version should match your epinio deployment
        - image: "ghcr.io/epinio/epinio-server:v1.8.1"
          name: epinio-push
          volumeMounts:
          - name: settings
            mountPath: "/settings/"
            readOnly: true  
          - name: tmp
            mountPath: /tmp
            readOnly: false
          env:
          - name: EPINIO_SETTINGS
            value: "/settings/settings.yaml"
          command:
          - /epinio 
          args:
          - push
          - "--name"
          # This is the name of the app to push
          - test12factor
          workingDir: /workspace/source
        volumes:
        - name: settings
          secret:
            secretName: epinio-creds
        - name: tmp
          emptyDir: {}
```
