### ISSUE TITLE
Document how to create CR manually

### ISSUE THREAD

**Issue by mmartin24** [epinio/docs#375]
We should document somewhere (to be discussed) how to recover Epinio app to be visible by CLI again if deleted. 

Example:

```
cat <<EOF | kubectl apply -f -
apiVersion: application.epinio.io/v1
kind: App
metadata:
  annotations:
    epinio.io/created-by: admin
  name: jenkins-epinio
  namespace: workspace
spec:
  chartname: standard
  imageurl: jenkins/jenkins
  origin:
    container: jenkins/jenkins
  routes:
  - jenkins-epinio.192.168.16.3.omg.howdoi.website
EOF
```

Related issue: https://github.com/epinio/epinio/issues/2623#top  

---
Alternative: (edited. added post-initial description)

- Deploy a similar temporary app. Get app resources yaml from temporary and adapt that for the original one.
```
 k get apps.application.epinio.io jenkins-epinio -n workspace -o yaml > /tmp/sample.yaml
```

Modify & apply it
```
k apply -f /tmp/sample.yaml         
```

- Delete temporary app
```
epinio app delete temporary-app
```

App should re-appear
