### ISSUE TITLE
Update the `epinio` CLI installation

### ISSUE THREAD

**Issue by enrichman** [epinio/docs#76]
Now `epinio` is available on `brew` 
- https://github.com/epinio/epinio/issues/1306

We have to update the documentation to show how to do this.

**Note:** remember to document both the `tap` (to have the latest version) and the `core` installation method.
- https://github.com/epinio/homebrew-tap

- [ ] Update docs with installation from custom Epinio tap

## Nice to have

It will be nice to use `updatecli` to update the links to the latest version, so the user will have a working link and avoid to look for the released versions.

**PTAL**
- https://github.com/updatecli/website/pull/268
- https://github.com/updatecli/website/blob/master/updatecli/updatecli.d/installation.yaml#L25-L33

```yaml
targets:
  download-url:
    name: 'Update Installation URL'
    kind: file
    spec:
      file: content/docs/prologue/installation.adoc
      matchPattern: 'https://github.com/updatecli/updatecli/releases/download/(.*)/'
      replacePattern: 'https://github.com/updatecli/updatecli/releases/download/{{ source "updatecli" }}/'
    scmID: default
```
