### ISSUE TITLE
Missing information about websocket timeout in Advanced Topics

### ISSUE THREAD

**Issue by bdekany** [epinio/docs#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

If the staging process is long (ie. npm install in NodeJS) the CLI and UI may exprerience websocket timeout.

In case of nginx used as Ingress or Proxy you have to increase the read timeout

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "360s"```

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```markdown
- OS: SLES
- Architecture: x86
- Epinio Version: 0.7.3
- Cluster:
  - Provider: Self RKE2
  - Options:
  - Kubernetes Version: 1.21
```

### Logs

```markdown
EpinioServer/streamer-to-websockets: "msg"="failed to write to websockets" "error"="write tcp 10.42.244.102:8030->192.168.102.23:50482: write: broken pipe"
```
